Gophermart
MrTomSawyer/gothermart pull request #1
Opened 2023-07-19 14:30 UTC by MrTomSawyer

Максим, привет.
Первая версия сервиса тут. Пока без тестов, они на подходе

2023-07-27 07:53 UTC, maxlyaptsev requested changes

2023-07-27 07:53 UTC, maxlyaptsev commented on internal/app/entity/user.go
> +func (u *User) SetPassword(password string) {
хорошо бы тогда в структуре сделать PasswordHash не экспортируемым, иначе даем его менять напрямую

2023-07-27 07:53 UTC, maxlyaptsev commented on internal/app/entity/user.go
> +func (u *User) SetBalance(b interface{}) error {
тут хорошо бы дженерики использовать (будет дальше в курсе)

2023-07-27 07:53 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +				return
а что будет в этом случае? Я правильно понял что заказ выбьется из канала и больше туда не попадет т.к. канал наполняется только в ручке добавления заказа?

2023-07-27 13:51 UTC, MrTomSawyer commented on internal/app/entity/user.go
> +func (u *User) SetBalance(b interface{}) error {
Учту

2023-07-27 14:34 UTC, MrTomSawyer commented on internal/app/entity/user.go
> +func (u *User) SetPassword(password string) {
сделано

2023-07-27 14:49 UTC, MrTomSawyer commented on internal/app/workers/accrual.go
> +				return
Да, ты верно понял - такой заказ обрабатываться не должен.
В техзадании сказано: "Статусы INVALID и PROCESSED являются окончательными."

Это означает что такой заказ уже однажды обрабатывался и снова обрабатывать его нет смысла.

2023-07-28 14:34 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +			_, err = pool.Exec(ctx, "UPDATE orders SET order_status=$1, accrual=$2 WHERE order_num=$3", order.Status, order.Accrual, orderID)
хорошо бы репозиторий как зависимость подтянуть, а не работать с сырыми запросами

2023-07-28 14:35 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +				return
не туда написал комментарий - интересуют и другие случаи - например выше в случае ошибки или ниже - когда мы выходим из обработки. У нас не будет возможности обраотать еще раз - ошибка может быть кратковременной - заказ например еще не добрался до сервиса accrual или не посчиталось значение

2023-07-28 14:40 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +			_, err = pool.Exec(ctx, "UPDATE users SET balance=$1 WHERE id=$2", user.Balance, userID)
выше открыли транзакцию, но запросы делаются из пула свободных конектов, сотв. не в транзакции
а еще лучше добавлять измение баланса, точное значение может перетереть данные, которые записались в параллельном потоке в промежутке между тем как получили баланс и начали его обновлять. Зависит от уровня изоляции
```suggestion
			_, err = tx.Exec(ctx, "UPDATE users SET balance=balance+$1 WHERE id=$2", user.Balance, userID)
```

2023-08-01 14:50 UTC, MrTomSawyer commented on internal/app/workers/accrual.go
> +			_, err = pool.Exec(ctx, "UPDATE orders SET order_status=$1, accrual=$2 WHERE order_num=$3", order.Status, order.Accrual, orderID)
done

2023-08-01 14:51 UTC, MrTomSawyer commented on internal/app/workers/accrual.go
> +				return
Переделал. Теперь канала нет. Воркер раз в некоторое время (по тикеру) заглядывает в базу, ищет там необработанные заказы и пытается обработать.

2023-08-01 16:10 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +		res, err = http.Get(url)
я бы рекомендовал использовать сторонний пакет, например resty - он возвращает ошибку в случае если код 299 и больше что довольно удобно

<img width="747" alt="image" src="https://github.com/MrTomSawyer/gothermart/assets/10906726/02e42d5c-5099-41d4-bda6-4671906825e4">

2023-08-01 16:28 UTC, maxlyaptsev requested changes

2023-08-01 16:28 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +					m.Lock()
не очень понял от чего защищает этот лок. Лучше конечно комментарии добавлять т.к. может уже и причины нет,  а удалять никто не будет т.к. страшно сломать что-то

2023-08-01 16:28 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +	go func() {
HandleOrders уже вызывается как  горутина - нет смысла делать "горутину в горутине". Лучше на самом деле писать обычные синхронные функции, а клиенту дать возможность запускать их так как хочется

2023-08-01 16:28 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +				}(orderID)
```suggestion
				go processOrder(orderID)
```

тут бы легче читалось если разделить логику - текущая функция отвечала бы за получение заказов, и периодический запуск обработки заказа. А вторая функция только обрабатывала один конкретный заказ

Каждая функция будет выполнять небольшую понятную работу

2023-08-01 16:28 UTC, maxlyaptsev commented on internal/app/workers/accrual.go
> +	retryInterval := 1 * time.Second
лучше такие вещи выносить в конфигурацию приложения
А для ретрая тоже есть свои пакеты  (https://github.com/cenkalti/backoff/tree/v4)
Пример реализации писал в пачке

2023-08-02 12:38 UTC, MrTomSawyer commented on internal/app/workers/accrual.go
> +	retryInterval := 1 * time.Second
вынес в конфиг

2023-08-02 12:50 UTC, MrTomSawyer commented on internal/app/workers/accrual.go
> +		res, err = http.Get(url)
Учту на будущее, спасибо

2023-08-02 12:50 UTC, MrTomSawyer commented on internal/app/workers/accrual.go
> +	go func() {
Ты прав, это бесполезный оверхед. Убрал

2023-08-02 16:29 UTC, maxlyaptsev approved these changes

2023-08-03 05:39 UTC, merged